const express = require("express");
const router = express.Router();
const reportController = require("../controllers/reportController");
const { verifyToken } = require("../middleware/authMiddleware");
const { authorizeRoles } = require("../middleware/roleMiddleware");
router.post("/", verifyToken, reportController.createReport);
router.get("/", reportController.getReports);
router.put("/:id/assign",verifyToken,authorizeRoles("admin"),reportController.assignReport);
router.get("/analytics/damaged-assets",reportController.getMostDamagedAssets);
router.put("/:id/status",verifyToken, authorizeRoles("repairer","admin"), reportController.updateReportStatus);
router.get("/analytics/repair-time", reportController.getAverageRepairTime);
module.exports = router;